
/*---------------------------------------MODULOS--------------------------------------------------------------------*/

/*MODULO => un modulo  es una division del codigo en secciones para que sea mas legible y mas modificable*/

/*EJ: 
no quiero tener este codigo en el main de js. por lo q creo otro urilizo => /*"archivo".mjs => Modulo de javascript*/
        /*y le paso las funciones*/

/*NUEVO ARCHIVO MJS*/

/*

const getPokemon2 =async () => {
    for(let i = 1; i< 51; i++){
            try{
            const resolve =await fetch('https://pokeapi.co/api/v2/pokemon/${1}')
            const data =await resolve.json
            console.log(data)
            }
            catch(error){
                // para devolver el error
            }
        }
} 

export {getPokemon2} // export es para exportar 
*/

/*En el HTML 
<script type="modue" src="./"></script>
*/ 



/*EN EL JS MAIN*/
// import {getPokemon} from "./url" 

